 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'
   schedule:
     - cron: '59 23 * * *'

 jobs:
   unittests:
     name: ${{ matrix.os }}, ${{ matrix.environment-file }}
     runs-on: ${{ matrix.os }}
     timeout-minutes: 90
     strategy:
       matrix:
         os: ['ubuntu-latest']
         environment-file: [.ci/39.yaml, .ci/310.yaml, .ci/311.yaml, .ci/311-DEV.yaml]
         include:
           - environment-file: .ci/311.yaml
             os: macos-latest
           - environment-file: .ci/311.yaml
             os: windows-latest
       fail-fast: false
     defaults:
       run:
         shell: bash -l {0}

     steps:
       - name: checkout repo
         uses: actions/checkout@v4

       - name: setup micromamba
         uses: mamba-org/setup-micromamba@v1
         with:
           environment-file: ${{ matrix.environment-file }}
           micromamba-version: 'latest'
       - name: install spglm via pip
         run: pip install --upgrade --no-deps git+https://github.com/pysal/spglm.git@main

       - name: install spreg via pip
         run: pip install spreg

       - name: install bleeding edge libpysal (only Ubuntu / Python 3.9)
         run: pip install git+https://github.com/pysal/libpysal.git@main
         if: matrix.os == 'ubuntu-latest' && contains(matrix.environment-file, 'DEV')

       - name: run tests - bash
         run: pytest

        #  -v mgwr --cov=mgwr tests/ --cov-report=xml --timeout=300

       - uses: codecov/codecov-action@v3
